# Generated by Django 3.1.6 on 2021-02-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=2000)),
                ('genres', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('r_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userid', models.BigIntegerField()),
                ('itemid', models.BigIntegerField()),
                ('rating', models.FloatField()),
                ('timestamp', models.TextField(max_length=2000)),
            ],
        ),
    ]
